### ISSUE TITLE
getting following build error

### ISSUE THREAD

**Issue by chaoranxie** [AtroxDev/haikunator#1]
```
Running setup.py egg_info for package haikunator
           Traceback (most recent call last):
             File "<string>", line 16, in <module>
             File "/usr/share/build/haikunator/setup.py", line 2, in <module>
               import haikunator
             File "haikunator/__init__.py", line 2, in <module>
               from six.moves import range
           ImportError: No module named six.moves
           Complete output from command python setup.py egg_info:
           Traceback (most recent call last):

         File "<string>", line 16, in <module>

         File "/usr/share/build/haikunator/setup.py", line 2, in <module>

           import haikunator

         File "haikunator/__init__.py", line 2, in <module>

           from six.moves import range

       ImportError: No module named six.moves
```

**Comment by Atrox** [comment]
Hmm, tried it and this seems fine for me. Which python version do you use?

**Comment by chaoranxie** [comment]
Python 2.7.6 on mac, it looks like i can do 
pip install six
pip install haikunator

but i can not do following where requirement.txt includes haikunator
pip install -r requirement.txt

**Comment by Atrox** [comment]
Thanks for the informations. I will take a look tomorrow and I will try to fix this. 
I want anyway to get rid of six because for such a small project that does not make sense at all.

**Comment by Atrox** [comment]
@chaoranxie could you try it again now with version 0.2.0? This should work now.

**Comment by chaoranxie** [comment]
works now
